import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import { openSans } from "@/utils/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${openSans.className} antialiased min-h-screen flex flex-col font-[family-name:var(--font-geist-sans)] border-[10px] border-indigo-900 bg-slate-300`}
			>
				<Header appName="Aimee App" />
				<main className="flex-1 p-24">{children}</main>
				<footer className="p-5 text-center">
					Aimee Tacchi App &copy; 2024
				</footer>
			</body>
		</html>
	);
}
